apiVersion: csi.ibm.com/v1
kind: CSIScaleOperator
metadata:
  name: ibm-spectrum-scale-csi
  namespace: ibm-spectrum-scale-csi-driver
spec:
  spectrumScale: quay.io/ibm-spectrum-scale/ibm-spectrum-scale-csi-driver:v2.12.0

  clusters:
    - id: "10186611170220879816"
      primary:
        primaryFs: fs0
      restApi:
        - guiHost: "10.243.145.103"
          guiPort: 8443
      secrets: mmapi-owning-secret
      secureSslMode: false

  pluginNodeSelector:
    - key: scale
      value: "true"

  # Force controller pods (provisioner, attacher, etc.) to run on GPU nodes only
  # where the DaemonSet driver pods are running with the CSI socket
  provisionerNodeSelector:
    - key: scale
      value: "true"
  attacherNodeSelector:
    - key: scale
      value: "true"
  resizerNodeSelector:
    - key: scale
      value: "true"
  snapshotterNodeSelector:
    - key: scale
      value: "true"
