apiVersion: v1
kind: Namespace
metadata:
  name: ibm-spectrum-scale-csi-driver
---
apiVersion: v1
kind: Secret
metadata:
  name: mmapi-owning-secret
  namespace: ibm-spectrum-scale-csi-driver
type: Opaque
stringData:
  username: admin
  password: "<OWNING_CLUSTER_TOKEN_SECRET>"
