apiVersion: v1
kind: Namespace
metadata:
  name: ibm-spectrum-scale-csi
---
# Secret for owning cluster (10.243.145.103)
apiVersion: v1
kind: Secret
metadata:
  name: mmapi-owning-secret
  namespace: ibm-spectrum-scale-csi
type: Opaque
stringData:
  username: admin
  password: "<OWNING_CLUSTER_TOKEN_SECRET>"
---
# Secret for accessing cluster (10.243.144.51)
apiVersion: v1
kind: Secret
metadata:
  name: mmapi-accessing-secret
  namespace: ibm-spectrum-scale-csi
type: Opaque
stringData:
  username: admin
  password: "<ACCESSING_CLUSTER_TOKEN_SECRET>"
