apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: gpfs-fileset
provisioner: spectrumscale.csi.ibm.com
parameters:
  volBackendFs: fs0
  clusterId: "10186611170220879816"
reclaimPolicy: Delete
allowVolumeExpansion: true
